### ISSUE TITLE
Multiple requirements.txt files, scripts - is this worth the trouble?  Requires more doco?

### ISSUE THREAD

**Issue by MikeTheCanuck** [hackoregon/backend-examplar-2018#24]
I look at the number of `requirements` files in this year's API repos and it makes my head spin.  Not because they aren't working (the variety of scripts out there, while also confusing, at least seem to successfully call the right file), but because as a non-expert in Python and Django, I'm not sure I would correctly guess which of these files I'd put new packages in - and whether I got all the scenarios (local dev, local staging, cloud staging, Travis?) right.

I can see the thinking behind it - keep only the files that are relevant to each scenario, so the build and run time are minimized.  I know that's a good goal - but I'm worried it sacrifices others' ability to reason out the variety of artifacts in which another developer has to make changes (requirements, scripts, maybe others?) to accommodate each of the scenarios.

I found it hard enough to keep `-l` and `-t` straight last year, and those at least were very discrete scenarios.  Maybe this is a problem that can be solved with documentation - I don't know if any of us will know, as we're becoming too close to the problem - but at the very least, let's get a very friggin clear explanation of which scripts and requirements files to use for what usage scenarios.

[Note: I'm probably confusing the flexibility of `package.json` in the node/JS world with probably-more-limited approaches in the `requirements.txt` Python world.  Maybe the `dependencies` vs `dev dependencies` distinction still isn't available for us in Python-land.]

(I'm harvesting inspiration for this issue from #18 where I started asking about out-of-scope issues to that PR.)

**Comment by bhgrant8** [comment]
More then open to further discussion on this but here is my thinking on this pattern:

1. It can be done better then my current model, following this [stackoverflow](https://stackoverflow.com/questions/17803829/how-to-customize-a-requirements-txt-for-multiple-environments?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa) answer, might be more clearer, renaming the base file as common.txt and using the recursion flag to link between files. Only import the one, and you could trace back from there

2. Generally though, using a requirements folder with split txt files for different environments is fairly standard python procedure. 

3. While I as well have used a single one and not worried about it, really there are some potential security risks if debug/testing packages are left in or certain changes not made when moving from dev to a live environment. 

4. Splitting out the dev dependencies from prod should put less downstream responsibility on ops to research what every python package is, in and whether it should remain in the deployed version. It also will make devs ask the question what is it? and why am i putting it in upfront, which, I would also argue is a good thing. 

5. Less questions like this: https://github.com/hackoregon/transportation-backend/blob/32b35a9b817ce8ac9f8d47c944e49a55bb96f85a/transDjango/requirements.txt#L21
😈 

Opening a new issue for question of the what environments we actually need because I am not fully clear on this either.

**Comment by znmeb** [comment]
I can tell you what the database container needs:
1. Port to map to the host. The default port is fine inside the Docker network
2. The `postgres` password.
3. A list of database users to create so that backups will restore.

**Comment by bhgrant8** [comment]
i am going to close as we have reworked the requirements.txt. if you have further questions/concerns fell free to reopen
